[package]
name = "uiua-pad-shared"
edition = "2021"
version = "0.1.0"
description = "Uiua pad web worker"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
uiua = { path = "../..", default-features = false}
