[package]
edition = "2021"
name = "site"
version = "0.1.0"

[dependencies]
base64 = "0.21.7"
comrak = "0.21.0"
console_error_panic_hook = "0.1.7"
enum-iterator = "2.0.0"
getrandom = {version = "0.2", features = ["js"]}
hound = "3.5.1"
image = "0.24.8"
instant = {version = "0.1.12", features = ['wasm-bindgen']}
js-sys = "0.3"
leptos = "0.6.5"
leptos_meta = {version = "0.6.5", features = ["csr"]}
leptos_router = {version = "0.6.5", features = ["csr"]}
pathdiff = "0.2.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
uiua = {path = "..", default-features = false, features = ["bytes", "batteries"]}
urlencoding = "2"
wasm-bindgen = "0.2.91"
wasm-bindgen-futures = "0.4.40"

[dependencies.web-sys]
features = [
  "CssStyleDeclaration",
  "Storage",
  "HtmlAudioElement",
  "HtmlBrElement",
  "Selection",
  "Node",
  "Clipboard",
  "ClipboardEvent",
  "DataTransfer",
  "Navigator",
  "Permissions",
  "ScrollIntoViewOptions",
  "ScrollBehavior",
  "ScrollLogicalPosition",
  "StorageManager",
  "FileReader",
  "EventInit",
  "DataTransfer",
  "File",
  "FileList",
]
version = "0.3.67"
