[package]
edition = "2021"
name = "site"
version = "0.1.0"

[dependencies]
base64 = "0.21.0"
comrak = "0.18.0"
console_error_panic_hook = "0.1.7"
enum-iterator = "1.4.1"
image = "0.24.5"
instant = { version = "0.1.12", features = ['wasm-bindgen'] }
js-sys = "0.3"
leptos = "0.5.0"
leptos_router = { version = "0.5.0", features = ["csr"] }
uiua = { path = "..", default-features = false }
urlencoding = "2"
wasm-bindgen = "0.2.84"

[dependencies.web-sys]
version = "0.3.61"
features = [
  "CssStyleDeclaration",
  "Storage",
  "HtmlAudioElement",
  "HtmlBrElement",
  "Selection",
  "Node",
  "Clipboard",
  "ClipboardEvent",
  "DataTransfer",
  "Navigator",
  "Permissions",
  "ScrollIntoViewOptions",
  "ScrollBehavior",
  "ScrollLogicalPosition",
  "EventInit",
]
