[package]
edition = "2021"
name = "site"
version = "0.1.0"

[dependencies]
base64 = "0.22.0"
comrak = "0.22.0"
console_error_panic_hook = "0.1.7"
enum-iterator = "2.0.0"
getrandom = {version = "0.2", features = ["js"]}
hound = "3.5.1"
image = "0.24.9"
js-sys = "0.3"
leptos = "0.6.11"
leptos_meta = {version = "0.6.11", features = ["csr"]}
leptos_router = {version = "0.6.11", features = ["csr"]}
pathdiff = "0.2.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
uiua = {path = "..", default-features = false, features = ["batteries", "web"]}
uiua-editor = {path = "../pad/editor"}
unicode-segmentation = "1.10"
urlencoding = "2"
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"

[dependencies.web-sys]
features = [
  "CssStyleDeclaration",
  "DomRect",
  "Storage",
  "HtmlAudioElement",
  "HtmlBrElement",
  "HtmlElement",
  "Selection",
  "Node",
  "Clipboard",
  "ClipboardEvent",
  "DataTransfer",
  "Navigator",
  "Permissions",
  "ScrollIntoViewOptions",
  "ScrollBehavior",
  "ScrollLogicalPosition",
  "StorageManager",
  "FileReader",
  "EventInit",
  "DataTransfer",
  "File",
  "FileList",
  "ResizeObserver",
  "ResizeObserverEntry",
  "Performance",
]
version = "0.3.70"

[features]
audio = [] # Dummy for rust-analyzer
