name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: sed
      run: sudo sed -i 's/azure\.//' /etc/apt/sources.list
    - name: apt update
      run: sudo apt-get update
    - name: Install deps
      run: sudo apt-get install libasound2-dev libudev-dev pkg-config libx11-dev
    - name: Install WASM target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose
    - name: Run interpreter tests
      run: cargo test --lib
    - name: Check feature combinations
      run: cargo run ./.github/features.ua
    - name: Run site tests
      run: cargo test -p site 
    - name: Check site
      run: cargo check -p site --target wasm32-unknown-unknown
